name: ManageWorkingTime
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configurations/ManageWorkingTime-Debug.xcconfig
  Release: Configurations/ManageWorkingTime-Release.xcconfig
schemes:
  ManageWorkingTime:
    build:
      targets:
        ManageWorkingTime: all
    run:
      config: Debug
      commandLineArguments:
        -FIRAnalyticsDebugEnabled: YES
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: false
fileGroups:
  - Configurations
packages:
  SwiftUICharts:
    url: https://github.com/AppPear/ChartView
    from: 1.5.3
    name: SwiftUICharts
targets:
  ManageWorkingTime:
    type: application
    platform: iOS
    sources:
      - ManageWorkingTime
    settings:
      CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: SwiftUICharts
    preBuildScripts:
      - name: SwiftGen
        script: |
                $PODS_ROOT/SwiftGen/bin/swiftgen config run --config $SRCROOT/ManageWorkingTime/SwiftGen/swiftgen.yml
    postCompileScripts:
      - name: Swiftlint
        script: Pods/SwiftLint/swiftlint autocorrect --format

  ManageWorkingTimeAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: ManageWorkingTimeTests
    dependencies:
      - target: ManageWorkingTime
